### ISSUE TITLE
Memory warning in sorter.

### ISSUE THREAD

**Issue by yjwoo14** [thomasmoelhave/tpie#213] opened 2016-07-13 08:01 UTC
Getting the following warning when sort() pipe is placed at the beginning of a virtual chunk.

Not enough phase 1 memory for 128 KB items and an open stream! (0 < 6310712)

**Comment by Tyilo** [comment] 2016-07-31 11:14
I can't reproduce it, maybe it was fixed in 45b042e75e9fe4da3b0818a9987e844cd51b64d8

Could you check it again?

**Comment by svendcsvendsen** [comment] 2016-07-31 12:17
This was fixed by @antialize last friday.

**Closed** 2016-07-31 12:18 UTC
